<?php require 'templates/layout/header.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<body class="custom-bg">
<?php if ($error): ?>
        <p><?=$error?></p>
        <?php endif ?>
    <form action="addGame" method="post">
        <div class="form-bg">
        <h2 class="text-center">Agregar juego</h2>
            <div class="mb-3 d-grid">
                <label class="form-label">Titulo</label>
                <input type="text" name = 'title' class="login-box" required>
            </div>
            <div class="mb-3 d-grid">
                <label class="form-label">Genero</label>
                <select class="form-select" aria-label="Default select example" name="genre">
                    <option selected>Selecciona genero</option>
                    <?php foreach ($genre as $genre): ?>
                    <option value="<?php echo $genre->id_genre?>">
                        <?php echo $genre->genre_name?>
                    </option>
                    <?php endforeach ?>
                </select>
            </div>
            <div class="mb-3 d-grid">
                <label class="form-label">Descripcion</label>
                <input type="text" name= 'description' class="login-box" required>
            </div>
            <div class="mb-3 d-grid">
                <label class="form-label">Imagen</label>
                <input type="url" name= 'image' class="login-box" required>
            </div>
            <div class="text-center">
                <button type="submit" name="add" class="btn-login">Agregar</button>
            </div>
        </div>
    </form>
</body>

<?php require 'templates/layout/footer.phtml';?>