<?php require 'templates/layout/header.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<body class="custom-bg">
    <?php if ($error): ?>
        <p><?=$error?></p>
        <?php endif ?>
<?php foreach ($genre as $genre): ?>
    <form action="editGenre/<?php echo $genre->id_genre?>" method="post">
        <div class="form-bg">
        <h2 class="text-center">Editar genero</h2>
            <div class="mb-3 d-grid">
                <label class="form-label">Genero</label>
                <input type="text" name = 'genre' class="login-box" value="<?php echo $genre->genre_name?>" required>
            </div>
            <div class="text-center">
                <button type="submit" class="btn-login">Editar</button>
            </div>
        </div>
    </form>
<?php endforeach ?>
</body>

<?php require 'templates/layout/footer.phtml';?>