<?php require 'templates/layout/header.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<?php foreach ($game as $game):?>

<body class="custom-bg">
    <div class="col-12">
        <div class="d-flex m-4 custom-page">
            <img src="<?php echo $game->image?>" alt="gameCover" class="rounded-4 m-3 custom-size">
            <div class="m-4">
                <h4><?php echo $game->title?></h4>
                <p><?php echo $game->genre?></p>
                <p><?php echo $game->description?></p>
            </div>
        </div>
    </div>
</body>

<?php endforeach ?>
<?php require 'templates/layout/footer.phtml';?>