<?php require 'templates/layout/header.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<div class="container-fluid bg-dark text-white">
    <div class="row">
    <div class="categories col-2">
        <h3>Categorias</h3>
        <p>Action</p>
        <p>Arena Fighter</p>
    </div>
        <div class="games col-10">
            <div class="container d-grid gap-3">
                <div class="row justify-content-center">
                    <?php foreach ($games as $game): ?>
                    <div class="col-3 border rounded-4 text-center m-4">
                        <img src="<?php echo $game->image?>" alt="game" class="game-img">
                        <h4><?php echo $game->title?></h4>
                        <p><?php echo $game->genre?></p>
                    </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php require 'templates/layout/footer.phtml';?>