<!-- Header -->
<?php require 'templates/layout/header.phtml';?>

<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<body class="custom-bg body-all">

    <!-- Categorias -->

    <div class="col-12">
        <div class="p-2 d-flex gap-5 justify-content-center category">
            <a href="home" class="text-decoration-none text-white"><h5>Todos</h5></a>
            <?php foreach ($genre as $genre): ?>
                <a href="home/<?php echo $genre->id_genre?>" class="text-decoration-none text-white"><h5><?php echo $genre->genre_name?></h5></a>
                <?php if($this->user): ?>
                <div>
                    <a href="showEditGenre/<?php echo $genre->id_genre?>"><img class="categoryIcon text-start" src="sources/editarIcono.png" alt=""></a>
                    <a href="deleteGenre/<?php echo $genre->id_genre?>"><img class="categoryIcon text-start" src="sources/eliminarIcono.png" alt=""></a>
                </div>
                <?php endif ?>
            <?php endforeach ?>
        </div>
    </div>

    <!-- Botones para agregar juegos y categorías, alineados a la derecha -->

    <?php if($this->user): ?>
        <div class="text-center p-2 ">
            <a href="showAddGame" class="btn btn-success">Agregar Juego</a>
            <a href="showAddGenre" class="btn btn-success">Agregar Genero</a>
        </div>
    <?php endif ?>

    <!-- Main body -->  

    <div class="games col-12">
        <div class="container d-grid">
            <div class="row justify-content-center">
                <?php foreach ($games as $game): ?>
                    <div class="col-3 custom-page text-center m-4">
                        <a href= "game/<?php echo $game->id?>" class="text-decoration-none text-white">
                        <img src="<?php echo $game->image?>" alt="game" class="game-img">
                        <h4><?php echo $game->title?></h4>
                        </a>
                        <p><?php echo $game->genre_name?></p>
                        <?php if($this->user): ?>
                        <div class="d-flex justify-content-center gap-2 p-2">
                            <a href="showEditGame/<?php echo $game->id?>" class="btn btn-success">Editar</a>
                            <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal<?php echo $game->id; ?>">Eliminar</button>
                        </div>
                        <?php endif ?>
                    </div>

                    <!-- Modal de confirmación -->
                    
                    <div class="modal fade" id="confirmDeleteModal<?php echo $game->id; ?>" tabindex="-1" aria-labelledby="confirmDeleteLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title text-dark">Confirmar Eliminación</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-dark">
                                    ¿Estás seguro de que deseas eliminar este juego?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                    <a href="deleteGame/<?php echo $game->id?>" class="btn btn-danger">Eliminar</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</body>

<!-- Footer -->

<?php require 'templates/layout/footer.phtml';?>