<?php require 'templates/layout/header.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<body class="custom-bg">
    <div class="categories col-12">
        <div class="p-2 d-flex gap-5 align-items-center">
            <h4>Categorias</h4>
            <p>Accion</p>
            <p>Arena Fighter</p>
        </div>
    </div>
    <div class="games col-12">
        <div class="container d-grid gap-3">
            <div class="row justify-content-center">
                <?php foreach ($games as $game): ?>
                <div class="col-3 custom-page text-center m-4">
                    <a href= "game/<?php echo $game->id?>" class="text-decoration-none text-white">
                    <img src="<?php echo $game->image?>" alt="game" class="game-img">
                    <h4><?php echo $game->title?></h4>
                    </a>
                    <p><?php echo $game->genre?></p>
                </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</body>

<?php require 'templates/layout/footer.phtml';?>