<?php require 'templates/layout/header-login.phtml';?>
<link rel="stylesheet" href="css/style.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<?php if ($error): ?>
    <div class="alert alert-danger"><?= $error ?></div>
<?php endif ?>

<body class="body-login">
    <div class="div-login">
        <form class="m-5" action='login' method = 'post'>
            <div class="form-bg">
                <div class="mb-3 d-grid">
                    <label class="form-label">Usuario</label>
                    <input type="name" name = 'name' class="login-box" required>
                </div>
                <div class="mb-3 d-grid">
                    <label class="form-label">Contraseña</label>
                    <input type="password" name= 'password' class="login-box" required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn-login">Iniciar sesion</button>
                </div>
            </div>
        </form>
    </div>
</body>
    
<?php require 'templates/layout/footer.phtml';?>