<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Footer</title>
  </head>
  <body>
    <footer class="bg- text-center text-lg-start bottom-0 text-white">
      <div class="text-center p-3" style="background-color: #151515">
        © 2024 Copyright: SkibidiGames
      </div>
    </footer>
  </body>
</html>

<!-- fixed-bottom -->