<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>SkibidiGames</title>
</head>
  <body>
    <nav class="navbar navbar-expand-sm header">
      <div class="container-fluid">
        <a class="text-decoration-none text-dark d-flex gap-2" href="home">
          <img src="sources/skibidiLogo.png" alt="" class="img-logo">
          <h4 class="d-flex align-items-center">SkibidiGames</h4>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end">
          <ul class="navbar-nav gap-3">
          <?php if(!$this->user): ?>
            <li class="nav-item">
              <a class="btn-header text-decoration-none text-white" aria-current="page" href="showLogin">Iniciar sesion</a>
            </li>
            <?php endif; ?>
            <?php if($this->user): ?>
            <li class="nav-item">
              <a class="btn-header text-decoration-none text-white" aria-current="page" href="logout">Cerrar sesion</a>
            </li>
            <?php endif; ?>
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>